INSERT INTO admin (firstname, surname, email, `password`) VALUES ('admin', 'admin', 'admin@homies.com', 'b109f3bbbc244eb82441917ed06d618b9008dd09b3befd1b5e07394c706a8bb980b1d7785e5976ec049b46df5f1326af5a2ea6d103fd07c95385ffab0cacbc86');
/*The password is: password*/

/* Products */
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1881,'Armhair', 'chair', 555, 80,'You can really loosen up and relax in comfort because the high back on this chair provides extra support for your neck.', 'chair1_p1.jpg#chair1_p2.jpg#chair1_p3.jpg#chair1_p4.jpg#chair1_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1882,'Desk Chair', 'chair', 15, 35,'You can lean back with perfect balance, as the tilt tension mechanism automatically adjusts the resistance to suit your weight and movements.', 'chair2_p1.jpg#chair2_p2.jpg#chair2_p3.jpg#chair2_p4.jpg#chair2_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1883,'Chair', 'chair', 5, 25,'You sit comfortably thanks to the restful flexibility of the scooped seat and shaped back.The self-adjusting plastic feet adds stability to the chair.', 'chair3_p1.jpg#chair3_p2.jpg#chair3_p3.jpg#chair3_p4.jpg#chair3_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1884,'Corner Couch', 'couch', 5, 450,'The sofa''s sections can be combined in different ways to get a size and shape that suits you. If you ever need a larger sofa, you can always add a section or two.Deep seat cushions with a top layer of fibre balls and plenty of comfortable back cushions makes the sofa feel soft and inviting.', 'sofa1_p1.jpg#sofa1_p2.jpg#sofa1_p3.jpg#sofa1_p4.jpg#sofa1_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1885,'Leather Couch', 'couch', 5, 800,'The cover is made of aniline leather which is the finest type of leather of the highest quality. As it ages, it becomes softer and gets a darker tone and fine patina.Aniline leather has an unaltered surface that is treated with just a thin, protective coating. This gives it great breathability while retaining its natural look with marks that make each cover unique.', 'sofa2_p1.jpg#sofa2_p2.jpg#sofa2_p3.jpg#sofa2_p4.jpg#sofa2_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1886,'Bed Sofa', 'couch', 5, 350,'This sofa converts quickly and easily into a spacious bed when you remove the back cushions and pull out the underframe.Sofa, chaise longue and double bed in one.', 'sofa3_p1.jpg#sofa3_p2.jpg#sofa3_p3.jpg#sofa3_p4.jpg#sofa3_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1887,'Small Dinning Table', 'table', 5, 50,'Small, neat dimensions make the table easy to furnish with, even when space is limited.A round table, with soft edges, gives a relaxed impression in a room.', 'table1_p1.jpg#table1_p2.jpg#table1_p3.jpg#table1_p4.jpg#table1_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1888,'Working Desk', 'table', 5, 100,'You can mount the tabletop at a height that suits you since the legs are adjustable between 62 and 76 cm.', 'table2_p1.jpg#table2_p2.jpg#table2_p3.jpg#table2_p4.jpg#table2_p5.jpg');
INSERT INTO product (id, title, category, stock, price, description, photos) VALUES (1889,'Coffee Table', 'table', 5, 80,'Separate shelf for magazines, etc. helps you keep your things organised and the table top clear.', 'table3_p1.jpg#table3_p2.jpg#table3_p3.jpg#table3_p4.jpg#table3_p5.jpg');
